"""Added drug_allergy field

Revision ID: 413fddb2bead
Revises: a0e73b3c1dd3
Create Date: 2025-07-31 17:25:26.684189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '413fddb2bead'
down_revision = 'a0e73b3c1dd3'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('member', schema=None) as batch_op:
     # Step 1: Add column as nullable
        batch_op.add_column(sa.Column('drug_allergy', sa.String(length=200), nullable=True))

    # Step 2: Populate existing rows with default value
    op.execute("UPDATE member SET drug_allergy = '' WHERE drug_allergy IS NULL")

    # Step 3: Make column NOT NULL
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.alter_column('drug_allergy', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.drop_column('drug_allergy')

    # ### end Alembic commands ###
