"""Increase diagnosis name length to 1000

Revision ID: 899c182fb28c
Revises: 413fddb2bead
Create Date: 2025-08-13 09:13:26.298114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '899c182fb28c'
down_revision = '413fddb2bead'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnosis', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=1000),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnosis', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###
