"""Added underlying field to Member

Revision ID: a0e73b3c1dd3
Revises: 
Create Date: 2025-07-30 17:17:57.517269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0e73b3c1dd3'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    with op.batch_alter_table('member', schema=None) as batch_op:
        # Step 1: Add column as nullable
        batch_op.add_column(sa.Column('underlying', sa.String(length=200), nullable=True))

    # Step 2: Populate existing rows with default value
    op.execute("UPDATE member SET underlying = '' WHERE underlying IS NULL")

    # Step 3: Make column NOT NULL
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.alter_column('underlying', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.drop_column('underlying')

    # ### end Alembic commands ###
